[build]
  command = "npm run build"
  publish = "dist"

# Force SPA routing (also covered by _redirects but this is a safety net)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Example: API proxy (uncomment and adjust if you want to proxy backend)
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-api.example.com/:splat"
#   status = 200
#   force = true

# Security headers (optional baseline)
# [[headers]]
#  for = "/*"
#  [headers.values]
#    X-Frame-Options = "DENY"
#    X-Content-Type-Options = "nosniff"
#    Referrer-Policy = "strict-origin-when-cross-origin"
#    Permissions-Policy = "geolocation=()"
